title: 2016 Presidential Election Predictions
description: > 
    Statistical predictions for the electoral college in the 2016 U.S. 
    presidential election.
url: "https://corymccartan.github.io/" 
baseurl: "/election-2016"

sass:
    style: compressed

gems:
    - jekyll-assets
