#!/usr/bin/env bash

rm -f output/history.csv
touch output/history.csv

for day in {5..30}
do
    ./run 7e4 --date 5/$day/2016
done

for day in {1..20}
do
    ./run 7e4 --date 6/$day/2016
done

cd ..
git add .
git commit -m 're-run of model'
./update
