#!/usr/bin/env bash

git push
git checkout gh-pages --quiet
git pull
git checkout master --quiet
JEKYLL_ENV=production
cd client
jekyll build
cd ..
git subtree push --prefix client/_site origin gh-pages

