#!/usr/bin/env bash

git push
JEKYLL_ENV=production
pushd client
jekyll build
popd

dir=`mktemp -d`
mv client/_site/* $dir/
git checkout gh-pages --quiet
git rm -rf *
mv $dir/* ./
git add * && git commit -m 'update'
git push origin -f gh-pages
git checkout master --quiet
