#!/usr/bin/env bash

rm -f output/president-history.csv
touch output/president-history.csv

for day in {5..31}
do
    echo MAY $day
    ./run 1e5 --date 5/$day/2016
done

for day in {1..30}
do
    echo JUNE $day
    ./run 1e5 --date 6/$day/2016
done

for day in {1..13}
do
    echo JULY $day
    ./run 1e5 --date 7/$day/2016
done

cd ..
git add .
git commit -m 're-run of model'
./update

cd president
