#!/usr/bin/env bash

rm -f output/president-history.csv
touch output/president-history.csv

for day in {8..30}
do
    echo JUNE $day
    ./run 5e4 --date 6/$day/2016
done

for day in {1..31}
do
    echo JULY $day
    ./run 1e5 --date 7/$day/2016
done

for day in {1..8}
do
    echo AUGUST $day
    ./run 1e5 --date 8/$day/2016
done

./run 5e5

cd ..
git add .
git commit -m 're-run of presidential model'
./deploy

cd president
