#!/usr/bin/env bash

rm -f output/house-history.csv
touch output/house-history.csv

for day in {1..30}
do
    echo JUNE $day
    ./run 4e4 --date 6/$day/2016
done

for day in {1..31}
do
    echo JULY $day
    ./run 4e4 --date 7/$day/2016
done

for day in {1..1}
do
    echo AUGUST $day
    ./run 5e4 --date 8/$day/2016
done

./run 1e5

cd ..
git add .
git commit -m 're-run of house model'

cd house
